### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by lingr7** [rokoDev/VersionHelper#1]
i only have some konwledge about cmake transparment info to .h.

**Comment by lingr7** [comment]
in cmake ,add .cmake like such sa
```cmake
include( "cmake/versioninfo/VersionHelper/VersionInfoUtils.cmake" )
include( "cmake/versioninfo/VersionHelper/GenerateGitInfo.cmake" )
include( "cmake/versioninfo/VersionHelper/GenerateByConfigure.cmake" )
```
what .h need #include in code file?
like
```cpp
#include "version_info.h"
```
ok?

**Comment by lingr7** [comment]
is it support build time?

**Comment by rokoDev** [comment]
Hi @lingr7. I could not respond earlier because today I was celebrating Christmas(Jesus Christ' birthday).
I just have added [user manual](https://github.com/rokoDev/VersionHelper/blob/master/README.md). Hope this can help you(`#include` example provided in the end of `README.md`).
And currently there is no support for build time. But if you need it I think that I could add this feature or accept your pull request if you have any.
Do not hesitate to ask me if something in my code is unclear or you have any remarks.

**Comment by rokoDev** [comment]
> is it support build time?

if by saying "build time" you mean build duration or timestamp when build was started then I think it is pointless because in this case reproducible builds are not possible. But it makes sense if you mean to add function that returns value of `git log -1 --pretty=%ct`

**Comment by lingr7** [comment]
> > is it support build time?
> 
> if by saying "build time" you mean build duration or timestamp when build was started then I think it is pointless because in this case reproducible builds are not possible. But it makes sense if you mean to add function that returns value of `git log -1 --pretty=%ct`

Later I implemented build time with other lib,which using cmake's  .in file template mechanism create .h.in file . Build time was possible, but was later found to be of little use, and a commit time is more likely to reflect debug milestones，yes, also use git command to get git log commit info.-v --version to offer git commit log info.

**Comment by rokoDev** [comment]
> > > is it support build time?
> > 
> > 
> > if by saying "build time" you mean build duration or timestamp when build was started then I think it is pointless because in this case reproducible builds are not possible. But it makes sense if you mean to add function that returns value of `git log -1 --pretty=%ct`
> 
> Later I implemented build time with other lib,which using cmake's .in file template mechanism create .h.in file . Build time was possible, but was later found to be of little use, and a commit time is more likely to reflect debug milestones，yes, also use git command to get git log commit info.-v --version to offer git commit log info.

So should I add support for `git log -1 --pretty=%ct` or `git --version` or for both?

**Comment by lingr7** [comment]
> > > > is it support build time?
> > > 
> > > 
> > > if by saying "build time" you mean build duration or timestamp when build was started then I think it is pointless because in this case reproducible builds are not possible. But it makes sense if you mean to add function that returns value of `git log -1 --pretty=%ct`
> > 
> > 
> > Later I implemented build time with other lib,which using cmake's .in file template mechanism create .h.in file . Build time was possible, but was later found to be of little use, and a commit time is more likely to reflect debug milestones，yes, also use git command to get git log commit info.-v --version to offer git commit log info.
> 
> So should I add support for `git log -1 --pretty=%ct` or `git --version` or for both?

no. may be `git log -1 --pretty=%ci`
